name: Build Solana Programs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.75.0
      
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.31/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      
      - name: Build Programs
        run: cargo build-sbf
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: solana-programs
          path: target/deploy/*.so
